import { act, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { demoCases } from './data/demo/catalog'

afterEach(() => vi.useRealTimers())
describe('series interface', () => {
  it('filters by category, supports both side previews with two cases and centers a single case', async () => {
    const user=userEvent.setup()
    const {container}=render(<App />)
    await user.click(screen.getByRole('button',{name:'乳腺癌'}))
    expect(screen.getByRole('heading',{name:demoCases[4].shortTitle})).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:/查看上一个病例/}))
    expect(screen.getByRole('heading',{name:demoCases[5].shortTitle})).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:/查看下一个病例/}))
    expect(screen.getByRole('heading',{name:demoCases[4].shortTitle})).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'GEJ腺癌'}))
    expect(container.querySelectorAll('.featured-case-preview')).toHaveLength(0)
    await user.click(screen.getByRole('button',{name:'开始查房'}))
    await user.click(screen.getByRole('tab',{name:'病程轴'}))
    expect(screen.getByRole('tabpanel', { name: '病程轴' })).toHaveTextContent(demoCases[8].timeline[0].detail)
    await user.click(screen.getByRole('button',{name:'开始模拟查房'}))
    expect(screen.getByRole('button',{name:'提交答案'})).toBeDisabled()
    await user.click(screen.getByRole('button',{name:'回顾病例资料'}))
    const dialog=screen.getByRole('dialog',{name:'病例资料'})
    await user.click(within(dialog).getByRole('tab',{name:'病程轴'}))
    expect(dialog).toHaveTextContent(demoCases[8].timeline[0].detail)
    await user.click(within(dialog).getByRole('button',{name:'关闭弹窗'}))
    for(let i=0;i<5;i++){
      await user.click(screen.getAllByRole('radio')[demoCases[8].questions[i].correctIndex])
      await user.click(screen.getByRole('button',{name:'提交答案'}))
      await user.click(screen.getByRole('button',{name:i===4?'查看查房总结':'下一题'}))
    }
    expect(screen.getByLabelText('查房得分 100分')).toBeInTheDocument()
    expect(screen.queryByRole('button',{name:/下一病例/})).not.toBeInTheDocument()
  })
  it('uses a real file selection, keeps cancellation, replaces files and generates a single resumable record', async () => {
    const user=userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button',{name:/创建专属查房/}))
    expect(screen.getByRole('button',{name:'生成专属查房'})).toBeDisabled()
    const fileInput=screen.getByLabelText('病例文件')
    await user.upload(fileInput,new File(['fixture'],'病例A.pdf',{type:'application/pdf'}))
    fireEvent.change(fileInput,{target:{files:[]}})
    expect(screen.getByRole('status')).toHaveTextContent('病例A.pdf')
    await user.upload(fileInput,new File(['fixture'],'病例B.pdf',{type:'application/pdf'}))
    expect(screen.getByRole('status')).toHaveTextContent('病例B.pdf')
    await user.selectOptions(screen.getByLabelText('演示病例'),demoCases[8].id)
    vi.useFakeTimers()
    fireEvent.click(screen.getByRole('button',{name:'生成专属查房'}))
    fireEvent.click(screen.getByRole('tab',{name:'专属查房'}))
    for(let i=0;i<3;i++) await act(async()=>{vi.advanceTimersByTime(1000)})
    vi.useRealTimers()
    expect(screen.getByRole('dialog',{name:'查房已生成'})).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'稍后再说'}))
    expect(document.querySelectorAll('.private-record')).toHaveLength(1)
    await user.click(screen.getByRole('button',{name:/专属查房 01/}))
    await user.click(screen.getByRole('button',{name:'开始模拟查房'}))
    await user.click(screen.getAllByRole('radio')[1])
    await user.click(screen.getByRole('button',{name:'提交答案'}))
    await user.click(screen.getByRole('button',{name:'返回主页'}))
    await user.click(screen.getByRole('button',{name:/继续查房/}))
    expect(screen.getAllByRole('radio')[1]).toBeChecked()
    expect(screen.getByText('回答正确')).toBeInTheDocument()
  })
})
